// This file will be auto-generated by Supabase CLI
// For now, we'll create a placeholder
export type Database = {
  public: {
    Tables: {
      // Tables will be defined here after running:
      // npx supabase gen types typescript --project-id "your-project-id" > src/types/database.types.ts
    }
    Views: {
      // Views will be defined here
    }
    Functions: {
      // Functions will be defined here
    }
    Enums: {
      // Enums will be defined here
    }
    CompositeTypes: {
      // Composite types will be defined here
    }
  }
}